<a href="https://colab.research.google.com/github/nayema32/Pytorch/blob/main/Tensor_Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

addition

In [3]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

Addition Longhand

In [4]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

Substract

In [5]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

Sub Function

In [6]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

Multiplication

In [7]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

Division

In [10]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

Remainder Modulus

In [12]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
torch.remainder(tensor_b, tensor_b)

tensor([0, 0, 0, 0])

Exponents

In [14]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [15]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

Reassignment

In [18]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([16, 20, 24, 28])

In [20]:
tensor_a.add_(tensor_b)

# we already reassaigned tensor_a = tensor([16, 20, 24, 28]) above

tensor([26, 32, 38, 44])